from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Detail(object):
    def close(self):
        self.Detail.close()
        

    def setupUi(self, Detail):
        self.Detail = Detail
        Detail.setObjectName("Detail")
        Detail.resize(603, 336)
        self.buttonClose = QtWidgets.QPushButton(Detail)
        self.buttonClose.setGeometry(QtCore.QRect(480, 290, 75, 23))
        self.buttonClose.setObjectName("buttonClose")
        self.graphicsView = QtWidgets.QGraphicsView(Detail)
        self.graphicsView.setEnabled(True)
        self.graphicsView.setGeometry(QtCore.QRect(50, 70, 221, 201))
        self.graphicsView.setStyleSheet("background-color: rgb(207, 215, 255);")
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(Detail)
        self.label.setGeometry(QtCore.QRect(130, 80, 61, 21))
        self.label.setObjectName("label")
        self.graphicsView_2 = QtWidgets.QGraphicsView(Detail)
        self.graphicsView_2.setEnabled(True)
        self.graphicsView_2.setGeometry(QtCore.QRect(330, 70, 221, 201))
        self.graphicsView_2.setStyleSheet("background-color: rgb(207, 215, 255);")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label_2 = QtWidgets.QLabel(Detail)
        self.label_2.setGeometry(QtCore.QRect(410, 80, 61, 21))
        self.label_2.setObjectName("label_2")
        self.setPositif = QtWidgets.QTextEdit(Detail)
        self.setPositif.setGeometry(QtCore.QRect(160, 120, 80, 31))
        self.setPositif.setObjectName("setPositif")
        self.labelPositif = QtWidgets.QLabel(Detail)
        self.labelPositif.setGeometry(QtCore.QRect(85, 120, 41, 21))
        self.labelPositif.setObjectName("labelPositif")
        self.labelNegatif = QtWidgets.QLabel(Detail)
        self.labelNegatif.setGeometry(QtCore.QRect(85, 190, 51, 21))
        self.labelNegatif.setObjectName("labelNegatif")
        self.setNegatif = QtWidgets.QTextEdit(Detail)
        self.setNegatif.setGeometry(QtCore.QRect(160, 190, 80, 31))
        self.setNegatif.setObjectName("setNegatif")
        self.setDayaTarik = QtWidgets.QTextEdit(Detail)
        self.setDayaTarik.setGeometry(QtCore.QRect(440, 110, 80, 31))
        self.setDayaTarik.setObjectName("setDayaTarik")
        self.setAksesbilitas = QtWidgets.QTextEdit(Detail)
        self.setAksesbilitas.setGeometry(QtCore.QRect(440, 150, 80, 31))
        self.setAksesbilitas.setObjectName("setAksesbilitas")
        self.setFasilitas = QtWidgets.QTextEdit(Detail)
        self.setFasilitas.setGeometry(QtCore.QRect(440, 230, 80, 31))
        self.setFasilitas.setObjectName("setFasilitas")
        self.setKebersihan = QtWidgets.QTextEdit(Detail)
        self.setKebersihan.setGeometry(QtCore.QRect(440, 190, 80, 31))
        self.setKebersihan.setObjectName("setKebersihan")
        self.labelAksesbilitas = QtWidgets.QLabel(Detail)
        self.labelAksesbilitas.setGeometry(QtCore.QRect(360, 150, 61, 21))
        self.labelAksesbilitas.setObjectName("labelAksesbilitas")
        self.labelFasilitas = QtWidgets.QLabel(Detail)
        self.labelFasilitas.setGeometry(QtCore.QRect(360, 230, 51, 21))
        self.labelFasilitas.setObjectName("labelFasilitas")
        self.setKebersihan_2 = QtWidgets.QLabel(Detail)
        self.setKebersihan_2.setGeometry(QtCore.QRect(360, 190, 61, 21))
        self.setKebersihan_2.setObjectName("setKebersihan_2")
        self.labelDayatarik = QtWidgets.QLabel(Detail)
        self.labelDayatarik.setGeometry(QtCore.QRect(360, 110, 61, 21))
        self.labelDayatarik.setObjectName("labelDayatarik")
        self.label_9 = QtWidgets.QLabel(Detail)
        self.label_9.setGeometry(QtCore.QRect(200, 20, 191, 16))
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Detail)
        QtCore.QMetaObject.connectSlotsByName(Detail)
        self.buttonClose.clicked.connect(self.close)

    def setDetail(self,set_positif, set_negatif, set_dayatarik, set_aksesbilitas,set_kebersihan,set_fasilitas):
        self.setPositif.setText(str('%.5f' %set_positif))
        self.setNegatif.setText(str('%.5f' %set_negatif))
        self.setDayaTarik.setText(str('%.5f' %set_dayatarik))
        self.setAksesbilitas.setText(str('%.5f' %set_aksesbilitas))
        self.setKebersihan.setText(str('%.5f' %set_kebersihan))
        self.setFasilitas.setText(str('%.5f' %set_fasilitas))

    def retranslateUi(self, Detail):
        _translate = QtCore.QCoreApplication.translate
        Detail.setWindowTitle(_translate("Detail", "Details"))
        self.buttonClose.setText(_translate("Detail", "Close"))
        self.label.setText(_translate("Detail", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">SENTIMEN</span></p></body></html>"))
        self.label_2.setText(_translate("Detail", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">KATEGORI</span></p></body></html>"))
        self.labelPositif.setText(_translate("Detail", "<html><head/><body><p><span style=\" font-size:10pt;\">Positif </span></p></body></html>"))
        self.labelNegatif.setText(_translate("Detail", "<html><head/><body><p><span style=\" font-size:10pt;\">Negatif </span></p></body></html>"))
        self.labelAksesbilitas.setText(_translate("Detail", "<html><head/><body><p><span style=\" font-size:9pt;\">Aksesbilitas</span></p></body></html>"))
        self.labelFasilitas.setText(_translate("Detail", "<html><head/><body><p><span style=\" font-size:9pt;\">Fasilitas</span></p></body></html>"))
        self.setKebersihan_2.setText(_translate("Detail", "<html><head/><body><p><span style=\" font-size:9pt;\">Kebersihan</span></p></body></html>"))
        self.labelDayatarik.setText(_translate("Detail", "<html><head/><body><p><span style=\" font-size:9pt;\">Daya Tarik </span></p></body></html>"))
        self.label_9.setText(_translate("Detail", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#000000;\">DETAIL PREDIKSI</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Detail = QtWidgets.QDialog()
    ui = Ui_Detail()
    ui.setupUi(Detail)
    Detail.show()
    sys.exit(app.exec_())
